from __future__ import annotations

from PySide6.QtCore import Signal
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QPushButton, QSpinBox


class TimelineWidget(QFrame):
    addFrameRequested = Signal()
    previousFrameRequested = Signal()
    nextFrameRequested = Signal()
    overviewToggled = Signal(bool)
    deleteModeToggled = Signal(bool)
    reorderModeToggled = Signal(bool)
    clearRequested = Signal()
    importImageRequested = Signal()
    saveRequested = Signal()
    durationChanged = Signal(int)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName("Timeline")
        self.info = QLabel("Frame 1/1")
        self.info.setObjectName("FrameBadge")
        self.duration = QSpinBox()
        self.duration.setMinimumWidth(118)
        self.duration.setRange(20, 5000)
        self.duration.setValue(250)
        self.duration.setSuffix(" ms")
        self.duration.valueChanged.connect(self.durationChanged.emit)
        self.previous = QPushButton("<")
        self.previous.setObjectName("IconButton")
        self.previous.setToolTip("Ver frame anterior")
        self.next = QPushButton(">")
        self.next.setObjectName("IconButton")
        self.next.setToolTip("Ver frame siguiente")
        add = QPushButton("+")
        add.setObjectName("IconButton")
        add.setToolTip("Crear frame vacio")
        self.overview = QPushButton("Vista")
        self.overview.setCheckable(True)
        self.overview.setObjectName("Secondary")
        self.overview.setToolTip("Ver todos los patrones de la secuencia")
        self.delete = QPushButton("Eliminar")
        self.delete.setCheckable(True)
        self.delete.setObjectName("Danger")
        self.delete.setToolTip("Mostrar una X para eliminar frames")
        self.reorder = QPushButton("Reordenar")
        self.reorder.setCheckable(True)
        self.reorder.setObjectName("Secondary")
        self.reorder.setToolTip("Arrastrar frames para cambiar el orden")
        clear = QPushButton("Limpiar")
        import_image = QPushButton("Importar imagen")
        save = QPushButton("Guardar")
        self.previous.clicked.connect(self.previousFrameRequested.emit)
        self.next.clicked.connect(self.nextFrameRequested.emit)
        add.clicked.connect(self.addFrameRequested.emit)
        self.overview.toggled.connect(self.overviewToggled.emit)
        self.delete.toggled.connect(self._delete_toggled)
        self.reorder.toggled.connect(self._reorder_toggled)
        clear.clicked.connect(self.clearRequested.emit)
        import_image.clicked.connect(self.importImageRequested.emit)
        save.clicked.connect(self.saveRequested.emit)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(12, 10, 12, 10)
        layout.addWidget(self.overview)
        layout.addWidget(self.previous)
        layout.addWidget(self.info)
        layout.addWidget(self.next)
        layout.addWidget(self.duration)
        layout.addWidget(add)
        layout.addWidget(self.delete)
        layout.addWidget(self.reorder)
        layout.addStretch()
        layout.addWidget(clear)
        layout.addWidget(import_image)
        layout.addWidget(save)
        layout.addStretch()

    def set_info(self, frame_index: int, total: int, duration_ms: int) -> None:
        self.info.setText(f"Frame {frame_index + 1}/{total}")
        self.previous.setEnabled(frame_index > 0)
        self.next.setEnabled(frame_index < total - 1)
        self.duration.blockSignals(True)
        self.duration.setValue(duration_ms)
        self.duration.blockSignals(False)

    def _delete_toggled(self, checked: bool) -> None:
        if checked and self.reorder.isChecked():
            self.reorder.setChecked(False)
        self.deleteModeToggled.emit(checked)

    def _reorder_toggled(self, checked: bool) -> None:
        if checked and self.delete.isChecked():
            self.delete.setChecked(False)
        self.reorderModeToggled.emit(checked)
